#!/bin/bash
read -r -p "Are you sure? [y/N] " response
response=${response,,}    # tolower
if [[ "$response" =~ ^(yes|y)$ ]]
then
find . -type f | cat -n | while read n f; do mv "$f" "$n.wav"; done
fi
